### ISSUE TITLE
Error: hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by s0kil** [mmark-md/mmark-cli#11]
I keep getting this error when running `mmark-cli`:
```
$ mmark -i recipes.markdown -o recipes.html --template layout.html --ext-skylighting --ext-ghc-highlighter --ext-punctuation --ext-toc 2-6
mmark: recipes.markdown: hGetContents: invalid argument (invalid byte sequence)
```

```
$ file -i recipes.markdown 
recipes.markdown: text/plain; charset=utf-8
```

```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

The error seems to be caused by `readFile`: https://hackage.haskell.org/package/text-2.0/docs/Data-Text-IO.html#v:readFile
But I'm not sure why.

```
$ mmark --version
mmark 0.0.5.0 UNKNOWN UNKNOWN
using mmark     (library) 0.0.7.3
using mmark-ext (library) 0.2.1.3
```

**Comment by mrkkrp** [comment]
Functions like `readFile` depend on locale. What's surprising is that you are getting this with `LANG=en_US.UTF-8` set. Could you perhaps provide a minimal version of `recipes.markdown` so that I could try to reproduce it?

**Comment by s0kil** [comment]
- clone: https://github.com/digitallyinduced/ihp
- In the IHP directory
- `nix-shell --run "cd Guide; make all"`
 That will run `mmark`, which is where the error happens on my machine.

**Comment by mrkkrp** [comment]
It actually built fine for me. One thing you might try to check is whether `LANG` is set in the nix shell when you are building.

**Comment by mrkkrp** [comment]
It does indeed fail if the nix shell is pure. You might want to set `LANG = "en_US.UTF-8";` in your derivation.

**Comment by s0kil** [comment]
I got the project to build my compiling the latest version of `mmark-cli`, thank you for your help.
